import { mkdir, copyFile, stat, writeFile } from 'fs/promises'
import { dirname, resolve } from 'path'
import type { CliIO } from './types.js'

interface GenerateOptions {
  toolsPath: string
  baseUrl: string
  output: string
  serverName: string
  force: boolean
}

function parseArgs(args: string[]): { ok: true; opts: GenerateOptions } | { ok: false; error: string } {
  let toolsPath: string | undefined
  let baseUrl: string | undefined
  let output: string | undefined
  let serverName = 'aiglue-server'
  let force = false
  for (let i = 0; i < args.length; i++) {
    const a = args[i]
    if (a === '--tools') toolsPath = args[++i]
    else if (a === '--base-url') baseUrl = args[++i]
    else if (a === '--output') output = args[++i]
    else if (a === '--name') serverName = args[++i]
    else if (a === '--force') force = true
    else return { ok: false, error: `unknown argument: ${a}` }
  }
  if (!toolsPath) return { ok: false, error: 'missing --tools <path>' }
  if (!baseUrl) return { ok: false, error: 'missing --base-url <url>' }
  if (!output) return { ok: false, error: 'missing --output <dir>' }
  return {
    ok: true,
    opts: {
      toolsPath: resolve(toolsPath),
      baseUrl,
      output: resolve(output),
      serverName,
      force,
    },
  }
}

async function exists(path: string): Promise<boolean> {
  try {
    await stat(path)
    return true
  } catch {
    return false
  }
}

async function writeIfMissing(content: string, dest: string, force: boolean, io: CliIO): Promise<void> {
  await mkdir(dirname(dest), { recursive: true })
  if (!force && (await exists(dest))) {
    io.stderr(`skipped ${dest} (already exists, use --force to overwrite)\n`)
    return
  }
  await writeFile(dest, content, 'utf-8')
  io.stdout(`wrote ${dest}\n`)
}

async function copyIfMissingFile(src: string, dest: string, force: boolean, io: CliIO): Promise<void> {
  await mkdir(dirname(dest), { recursive: true })
  if (!force && (await exists(dest))) {
    io.stderr(`skipped ${dest} (already exists, use --force to overwrite)\n`)
    return
  }
  await copyFile(src, dest)
  io.stdout(`wrote ${dest}\n`)
}

function buildClaudeDesktopSnippet(serverName: string, toolsAbsPath: string, baseUrl: string): string {
  // Plain JSON snippet — operator merges into their existing claude_desktop_config.json mcpServers map.
  const config = {
    mcpServers: {
      [serverName]: {
        command: 'npx',
        args: ['aiglue', 'mcp', 'serve', '--tools', toolsAbsPath, '--base-url', baseUrl],
        env: { AIGLUE_AUTH_TOKEN: '<paste-token-here>' },
      },
    },
  }
  return JSON.stringify(config, null, 2) + '\n'
}

function buildReadme(serverName: string, toolsAbsPath: string, baseUrl: string): string {
  return `# ${serverName} — MCP install bundle

Generated by \`aiglue generate-mcp\`. Drop this folder anywhere on disk and follow the three steps below to register the server with Claude Desktop, Cursor, Cline, or any other MCP-compatible host.

## 1. Install \`@hhowi/aiglue-core\`

\`\`\`bash
npm install -g @hhowi/aiglue-core
# or run on demand without install: npx -y @hhowi/aiglue-core ...
\`\`\`

## 2. Merge the snippet into your host's MCP config

Open \`claude_desktop_config.json\` (Claude Desktop), \`mcp.json\` (Cursor), etc., and merge \`claude_desktop_config.snippet.json\` from this folder into the \`mcpServers\` map. Replace \`<paste-token-here>\` with the bearer token your upstream API expects.

Resolved values for this bundle:

- Server name: \`${serverName}\`
- tools.yaml path: \`${toolsAbsPath}\`
- Upstream base URL: \`${baseUrl}\`

## 3. Restart the host

Quit and reopen Claude Desktop / Cursor / Cline. The new server appears in the tool list — try \`@${serverName}\` to invoke a tool by hand.

---

Need to update the catalog later? Edit \`tools.yaml\` in place; the engine picks it up on next launch (or live if you wire \`engine.reload()\` into your hosting). The snippet stays valid as long as the absolute path does not move.
`
}

export async function runGenerateMCP(args: string[], io: CliIO): Promise<number> {
  const [first, ...rest] = args
  if (!first || first === '--help' || first === '-h') {
    io.stdout(
      'aiglue generate-mcp [options]\n' +
      '\n' +
      'options:\n' +
      '  --tools <path>      Path to the tools.yaml that the bundled server will load (required)\n' +
      '  --base-url <url>    Upstream API base URL (required)\n' +
      '  --output <dir>      Destination directory for the generated bundle (required)\n' +
      '  --name <name>       Server name advertised to the host (default: aiglue-server)\n' +
      '  --force             Overwrite existing files in the output directory\n',
    )
    return 0
  }

  const parsed = parseArgs([first, ...rest])
  if (!parsed.ok) {
    io.stderr(`${parsed.error}\n`)
    return 2
  }
  const { toolsPath, baseUrl, output, serverName, force } = parsed.opts

  if (!(await exists(toolsPath))) {
    io.stderr(`generate-mcp failed: tools file not found at ${toolsPath}\n`)
    return 1
  }

  try {
    await copyIfMissingFile(toolsPath, resolve(output, 'tools.yaml'), force, io)
    await writeIfMissing(
      buildClaudeDesktopSnippet(serverName, toolsPath, baseUrl),
      resolve(output, 'claude_desktop_config.snippet.json'),
      force,
      io,
    )
    await writeIfMissing(
      buildReadme(serverName, toolsPath, baseUrl),
      resolve(output, 'README.md'),
      force,
      io,
    )
    io.stdout(`bundle ready at ${output}\n`)
    return 0
  } catch (err) {
    io.stderr(`generate-mcp failed: ${err instanceof Error ? err.message : String(err)}\n`)
    return 1
  }
}
